=== FullAmigo/mineedu/json-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "タイトル"
        },
        "image": {
            "type": "string",
            "format": "uri",
            "description": "画像ファイルのパス (URI形式)"
        },
        "description": {
            "type": "string",
            "description": "説明"
        },
        "worldlink": {
            "type": "string",
            "format": "uri",
            "description": "ワールドへのパス (URI形式)"
        },
        "tags": {
            "type": "array",
            "description": "タグ",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "title",
        "image",
        "description",
        "tags"
    ]
}

=== FullAmigo/mineedu/worlds.json
[
    {
        "title": "Hour of Code 2024 ザ・ショー",
        "image": "images/8e43a570-4661-4257-929c-f676d374c0fc.png",
        "description": "プログラミングでオリジナルのミュージカルを作ろう！マイクラギャグを見つけてね。",
        "worldlink": "https://education.minecraft.net/world/8e43a570-4661-4257-929c-f676d374c0fc",
        "tags": [ "HourOfCode", "プログラミング", "エージェント", "シングルプレイ","日本語" ]
    },
    {
        "title": "ホイール・オブ・スティーブ",
        "image": "images/ace53da4-37e3-4b7a-9f08-258fd8de36a4.png",
        "description": "映画版マインクラフト公開記念ワールド。2つのチームに分かれてミニゲームで戦おう！8人までマルチプレイできます。",
        "worldlink": "https://education.minecraft.net/world/ace53da4-37e3-4b7a-9f08-258fd8de36a4",
        "tags": [ "eスポーツ", "ミニゲーム", "シングルプレイ", "マルチプレイ", "PvP","言語不問" ]
    },
    {
        "title": "グッドゲーム",
        "image": "images/47e794ed-3412-4a22-97c0-31e46e899a7c.png",
        "description": "オンラインゲームのマナーを学ぼう！",
        "worldlink": "https://education.minecraft.net/world/47e794ed-3412-4a22-97c0-31e46e899a7c",
        "tags": [ "オンラインゲーム", "リテラシー", "シングルプレイ", "日本語" ]
    },
    {
        "title": "スピードラン(ブロックビアードのゴールドレース)",
        "image": "images/a7633f27-a9a6-4bc0-bbb4-14748b05dfe7.png",
        "description": "マイクラのアスレでスピードを競おう！",
        "worldlink": "https://education.minecraft.net/world/a7633f27-a9a6-4bc0-bbb4-14748b05dfe7",
        "tags": [ "eスポーツ", "スピードラン", "シングルプレイ", "マルチプレイ", "アスレ" ,"言語不問"]
    },
    {
        "title": "Hour of Code AI",
        "image": "images/f55246a2-8c63-4e7e-99f0-8b3f84877f8a.png",
        "description": "楽しくAIを学ぼう！",
        "worldlink": "https://education.minecraft.net/world/f55246a2-8c63-4e7e-99f0-8b3f84877f8a",
        "tags": [ "HourOfCode", "AI", "プログラミング", "エージェント", "シングルプレイ","日本語" ]
    },
    {
        "title": "Hour of Code タイムクラフト",
        "image": "images/ab2dc481-6de5-4f0d-a87d-3fe115425620.png",
        "description": "タイムトラベルでいろんな歴史の旅をしよう！",
        "worldlink": "https://education.minecraft.net/world/ab2dc481-6de5-4f0d-a87d-3fe115425620",
        "tags": [ "HourOfCode", "歴史","プログラミング", "シングルプレイ","日本語" ]
    },
    {
        "title": "蜂体験(蜂で構築)",
        "image": "images/16367989-c6d3-4e03-9bad-1bf5966fd6d6.png",
        "description": "プレイヤーが蜂になって巣の中を探検できます！",
        "worldlink": "https://education.minecraft.net/world/16367989-c6d3-4e03-9bad-1bf5966fd6d6",
        "tags": [ "自然保護", "探検", "理科", "シングルプレイ", "マルチプレイ","日本語" ]
    },
    {
        "title": "アルテミス：ロケットビルド",
        "image": "images/8d87507b-de24-49fc-be3a-a340a143692b.png",
        "description": "ロケットの仕組みを学んだりロケットを作ったりできます",
        "worldlink": "https://education.minecraft.net/world/8d87507b-de24-49fc-be3a-a340a143692b",
        "tags": [ "理科", "物理", "シングルプレイ","日本語" ]
    },
    {
        "title": "みんなで自然保護",
        "image": "images/a427140c-7046-4e15-8092-f392a992b7b7.png",
        "description": "種をまくキャノン砲でマングローブ林を再生させよう！だんだんとCO2濃度が薄くなっていくのが楽しいですよ。",
        "worldlink": "https://education.minecraft.net/world/a427140c-7046-4e15-8092-f392a992b7b7",
        "tags": [ "理科", "自然保護", "シングルプレイ","日本語" ]
    },
    {
        "title": "データセンター体験(クラウドクラフト)",
        "image": "images/e38d1a93-e3f8-4198-9877-c28b464f47ea.png",
        "description": "データセンターの内部を社会見学しよう！",
        "worldlink": "https://education.minecraft.net/world/e38d1a93-e3f8-4198-9877-c28b464f47ea",
        "tags": [ "クラウド", "データセンター", "コンピュータ", "ネットワーク", "プログラミング", "シングルプレイ","日本語" ]
    },
    {
        "title": "宝探し",
        "image": "images/b36caba0-6e0c-4f20-b065-ad2f19614b7a.png",
        "description": "日記を読みながらミッションを遂行したり、お宝をさがしたりするワールドです。お宝を見つけたときはテンション上がります。",
        "worldlink": "https://education.minecraft.net/world/b36caba0-6e0c-4f20-b065-ad2f19614b7a",
        "tags": [ "宝探し", "物語", "シングルプレイ","マルチプレイ","英語" ]
    },
    {
        "title": "元素スカベンジャーハント",
        "image": "images/22b79cea-6a00-4298-951c-050e9a8f3f14.png",
        "description": "マイクラワールド内のアイテムを元素還元器にかけて元素をあつめよう！",
        "worldlink": "https://education.minecraft.net/world/22b79cea-6a00-4298-951c-050e9a8f3f14",
        "tags": [ "化学", "元素記号", "シングルプレイ","マルチプレイ","英語" ]
    },
    {
        "title": "サイバーなお城チャレンジ",
        "image": "images/69ae8e66-63f9-4313-bbf1-aa8c18aa4641.png",
        "description": "お城に忍び込んでくるキツネからにわとりを守ります。種を集めたりたまごを集めたりおおいそがし！",
        "worldlink": "https://education.minecraft.net/world/69ae8e66-63f9-4313-bbf1-aa8c18aa4641",
        "tags": [ "脱出", "挑戦", "シングルプレイ","マルチプレイ","英語" ]
    }
]
